"""filename2

Revision ID: 09552cdcde6f
Revises: 7aa8556fe313
Create Date: 2022-07-08 10:58:52.209722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09552cdcde6f'
down_revision = '7aa8556fe313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_three_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('photo_three_name')

    # ### end Alembic commands ###
