"""try3

Revision ID: 0df90706ab48
Revises: 9d263b8d9b84
Create Date: 2022-07-01 15:59:45.718228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df90706ab48'
down_revision = '9d263b8d9b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_post_id_posts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_post_id_posts'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_post_id_posts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_post_id_posts', 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
