"""removed filename attr

Revision ID: 140381cc7215
Revises: 2db6647a861e
Create Date: 2022-07-06 10:25:17.488760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140381cc7215'
down_revision = '2db6647a861e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_posts_filename', type_='unique')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_posts_filename', ['filename'])

    # ### end Alembic commands ###
