"""answered_user

Revision ID: 48082ddab3f0
Revises: 6524de85135a
Create Date: 2022-07-05 09:18:21.303298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48082ddab3f0'
down_revision = '6524de85135a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_user', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('answered_user')

    # ### end Alembic commands ###
