"""replied field in Message

Revision ID: 73cc8cb4ec93
Revises: c4878e2dcfeb
Create Date: 2022-07-03 07:26:01.314064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cc8cb4ec93'
down_revision = 'c4878e2dcfeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replied', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('replied')

    # ### end Alembic commands ###
