"""filename

Revision ID: 7aa8556fe313
Revises: 9480d0db1fb0
Create Date: 2022-07-08 10:58:17.155433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa8556fe313'
down_revision = '9480d0db1fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_one_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_two_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('photo_two_name')
        batch_op.drop_column('photo_one_name')

    # ### end Alembic commands ###
