"""inqury field added in User2

Revision ID: 944076d85603
Revises: a2d450c9beb7
Create Date: 2022-07-03 07:33:47.739878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944076d85603'
down_revision = 'a2d450c9beb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('inquiry',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('inquiry',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
