"""required for photo_one

Revision ID: 9480d0db1fb0
Revises: de455ee627a1
Create Date: 2022-07-08 06:35:39.447648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9480d0db1fb0'
down_revision = 'de455ee627a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('photo_one',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('photo_one',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###
