"""inqury field added in User

Revision ID: a2d450c9beb7
Revises: 73cc8cb4ec93
Create Date: 2022-07-03 07:27:40.774475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d450c9beb7'
down_revision = '73cc8cb4ec93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inquiry', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('inquiry')

    # ### end Alembic commands ###
