"""try5

Revision ID: c4878e2dcfeb
Revises: 0df90706ab48
Create Date: 2022-07-01 16:16:09.379142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4878e2dcfeb'
down_revision = '0df90706ab48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_post_id_posts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_post_id_posts'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_post_id_posts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_post_id_posts', 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
