"""empty message

Revision ID: d329a8c71c5d
Revises: 
Create Date: 2022-07-22 07:56:32.529361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd329a8c71c5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_user_id_users', 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_user_id_users'), 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_messages_user_id_users'), 'messages', type_='foreignkey')
    op.create_foreign_key('fk_messages_user_id_users', 'messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
