"""answered_user2

Revision ID: d9530c3d5fa8
Revises: 48082ddab3f0
Create Date: 2022-07-05 09:26:57.359946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9530c3d5fa8'
down_revision = '48082ddab3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_user2', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_answered_user2'), ['answered_user2'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_answered_user2'))
        batch_op.drop_column('answered_user2')

    # ### end Alembic commands ###
